import "./App.css";
import Demo from "./Demo";
import { WalletProvider } from "@txnlab/use-wallet";
import { walletProviders } from "./providers";

function App() {
    return (
        <>
            <head>
                <title>Create React App</title>
                <meta
                    name="description"
                    content="Generated by create react app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>

            <WalletProvider value={walletProviders}>
                <Demo />
            </WalletProvider>
        </>
    );
}

export default App;
