import { PeraWalletConnect } from "@perawallet/connect";
import "./App.css";
import Demo from "./Demo";
import {
    PROVIDER_ID,
    WalletProvider,
    useInitializeProviders,
} from "@txnlab/use-wallet";

function App() {
    const providers = useInitializeProviders({
        providers: [{ id: PROVIDER_ID.PERA, clientStatic: PeraWalletConnect }],
    });

    return (
        <>
            <head>
                <title>Create React App</title>
                <meta
                    name="description"
                    content="Generated by create react app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>

            <WalletProvider value={providers}>
                <Demo />
            </WalletProvider>
        </>
    );
}

export default App;
