name: Build, test and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nextjs:
    name: NextJS check and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd NextJS && yarn install --frozen-lockfile

      - name: Run build
        run: cd NextJS && yarn build

      - name: Deploy preview to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NEXTJS_NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NEXTJS_NETLIFY_SITE_ID }}
          build_directory: NextJS/.next

  nextjs-release:
    if: github.ref == 'refs/heads/main'
    name: Release
    needs: [nextjs]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # <--- override default gh token

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Deploy preview to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NEXTJS_NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NEXTJS_NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "NextJS prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: NextJS/.next
