name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nextjs:
    name: NextJS check and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd NextJS && yarn install --frozen-lockfile

      - name: Run build
        run: cd NextJS && yarn build


  react:
    name: React check and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd React && yarn install --frozen-lockfile

      - name: Run build
        env:
            CI: false
        run: cd React && yarn build

  vue:
    name: VueJS check and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd Vue && yarn install --frozen-lockfile

      - name: Run eslint
        run: cd Vue && yarn lint

      - name: Run build
        run: cd Vue && yarn build


  svelte:
    name: Svelte check and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd Svelte && yarn install --frozen-lockfile

      - name: Run check
        run: cd Svelte && yarn check

      - name: Run build
        run: cd Svelte && yarn build
