name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    nextjs:
        name: NextJS check and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm
                  cache-dependency-path: NextJS/package-lock.json

            - name: Install dependencies
              run: cd NextJS && npm ci

            - name: Run build
              run: cd NextJS && npm run build

    react:
        name: React check and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm
                  cache-dependency-path: React/package-lock.json

            - name: Install dependencies
              run: cd React && npm ci

            - name: Run build
              env:
                  CI: false
              run: cd React && npm run build

    vue:
        name: VueJS check and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm
                  cache-dependency-path: Vue/package-lock.json

            - name: Install dependencies
              run: cd Vue && npm ci

            - name: Run eslint
              run: cd Vue && npm run lint

            - name: Run build
              run: cd Vue && npm run build

    svelte:
        name: Svelte check and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm
                  cache-dependency-path: Svelte/package-lock.json

            - name: Install dependencies
              run: cd Svelte && npm ci

            - name: Run check
              run: cd Svelte && npm run check

            - name: Run build
              run: cd Svelte && npm run build
